CREATE DATABASE IF NOT EXISTS MIKUPROJECT;
USE MIKUPROJECT;

CREATE TABLE IF NOT EXISTS DOACOES (
    idDoacao INT AUTO_INCREMENT PRIMARY KEY,
    nomeDoador VARCHAR(50) NOT NULL,
    valorDoacao DOUBLE NOT NULL CHECK (valorDoacao > 0),
    dataDoacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modoPagamento ENUM('Cartao', 'Pix', 'Especie', 'Boleto') NOT NULL
);
